title: Jonas Samuelsson
logo: "/images/logo9.png"
description: > 
  Data analyst and demographer with a background in epidemiological and public health research. 
  Currently working as an analyst at The Swedish Dental and Pharmaceutical Benefits Agency (TLV).
  <br><br>
  <a href="https://www.linkedin.com/in/jonsam19/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
