title: Jonas Samuelsson
logo: "/images/oooo.plus_172.png"
description: > 
  <br><br>
  <a href="https://www.linkedin.com/in/jonas-samuelsson19/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
