title: Jonas Samuelsson
logo: "/images/logo7.png"
description: > 
  Demographer with a background in data analysis and epidemiological research performing statistical analyses in R, Markdown, and Shiny. 
  Highly knowledgeable in data management, data visualization and various statistical and research methods. 
  Posessess Master's Degree in Demography from Stockholm University.
  <br><br>
  Currently working at Karolinska Institute where I am researching the impact of COVID-19 on people's mental health and work-life.
  <br><br>
  <a href="https://www.linkedin.com/in/jonas-samuelsson19/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
